// Плагины, которые используются в проекте
plugins {
    id 'java-library'  // Подключает функциональность Java-библиотеки (можно создавать .jar)
}

// Места, откуда Gradle будет скачивать зависимости (библиотеки)
repositories {
    mavenCentral()  // Основной репозиторий Maven с открытыми библиотеками
}

// Все внешние библиотеки, которые нужны вашему проекту
dependencies {
    // Зависимости для тестов (будут доступны только в тестовом коде)
    testImplementation(
            "org.junit.jupiter:junit-jupiter:5.11.4",
            "com.codeborne:selenide:7.9.3"  // Selenide - фреймворк для тестирования веб-интерфейсов
    )
}

//Для того чтоб запускать тесты
test {
    useJUnitPlatform()
}